POST http://localhost:8083/connectors
Content-Type: application/json
Accept: application/json

{
  "name": "postgresql-sink",
  "config": {
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "tasks.max": "1",
    "topics": "summary-last-week",
    "connection.url": "jdbc:postgresql://postgresql:5432/devdb",
    "connection.user": "postgres",
    "connection.password": "postgres",
    "table.name.format": "weekly_summary",
    "auto.create": "true",
    "insert.mode": "upsert",
    "pk.mode": "record_key",
    "pk.fields": "user_id",
    "transforms": "hoistKey,hoistValue",

    "transforms.hoistKey.type": "org.apache.kafka.connect.transforms.HoistField$Key",
    "transforms.hoistKey.field": "user_id",

    "transforms.hoistValue.type": "org.apache.kafka.connect.transforms.HoistField$Value",
    "transforms.hoistValue.field": "amount",

    "value.converter": "org.apache.kafka.connect.converters.DoubleConverter",
    "value.converter.schemas.enable": "false",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "key.converter.schemas.enable": "false"
  }
}