app.streams.enabled: false
spring:
  application:
    name: streams-app
  jackson:
    serialization:
      INDENT_OUTPUT: true
  kafka:
    client-id: ${spring.application.name}
    bootstrap-servers:
      - localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
    listener:
      ack-mode: manual
    streams:
      application-id: ${spring.application.name}
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        schema.registry.url: http://localhost:8081

